name: TestWorkflow

on: 
  push: 
    branches: 
      - master
    paths-ignore:
      - "**/*.md"
      - "*.sh"
      - "Dockerfile"

jobs:
  test:
    container:
      image: rust:1.73-slim-bullseye
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test

    